### ISSUE TITLE
add technology

### ISSUE THREAD

**Issue by Harish-Soni1** [OfficialFindCoder/FindCoder-Reporting-Bugs#1]
add new more technologies :- 
- machine learning
- pyqt5
- computer vision
- nlp
- web3
- solidity

and more

**Comment by piyushsinghania** [comment]
- Electron
- Materialize
- Regex (Regular Expressions)

**Comment by kaustubhgupta** [comment]
- FastAPI
- Pandas
- NumPy
- Sklearn
- Plotly

**Comment by OfficialFindCoder** [comment]
> * solidity

Added

**Comment by OfficialFindCoder** [comment]
> add new more technologies :-
> 
> * machine learning
> * pyqt5
> * computer vision
> * nlp
> * web3
> * solidity
> 

Added++

**Comment by OfficialFindCoder** [comment]
> * Electron
> * Materialize
> * Regex (Regular Expressions)

Added ++

**Comment by OfficialFindCoder** [comment]
> * FastAPI
> * Pandas
> * NumPy
> * Sklearn
> * Plotly

Added ++
