### ISSUE TITLE
Sign up problem

### ISSUE THREAD

**Issue by deepak-singh5219** [OfficialFindCoder/FindCoder-Reporting-Bugs#105]
While completing my sign-up on the first form where it asks for username, if I put an underscore in the username the page doesn't proceeds and doesn't show any warning also. I struggled to complete my onboarding for a long time and when I just changed my username, it worked correctly.
I think usernames with special characters are not accepted, so it must show a warning or something so that user gets to know.
Just a problem I faced.
Thank You

**Comment by OfficialFindCoder** [comment]
@deepak-singh5219 We have Resolved the issue.
If you face it again or find any other issue please feel free to reopen the ticket.
Thanks
