### ISSUE TITLE
Add more cities

### ISSUE THREAD

**Issue by AnkitSuda** [OfficialFindCoder/FindCoder-Reporting-Bugs#11]
City in which I live is missing in City drop-down.
Add Churu, Bikaner and other less known cities as well.

**Comment by piyushsinghania** [comment]
@OfficialFindCoder I guess, may be it will be very difficult to add each city.
You can either add **other** as an option.

**Comment by OfficialFindCoder** [comment]
Giving other as option will be not useful for future of this platform. You just let us know, and we are adding more.
