### ISSUE TITLE
profile's social links are broken

### ISSUE THREAD

**Issue by tusharsnx** [OfficialFindCoder/FindCoder-Reporting-Bugs#110]
### Description:
The social links available on the user profile eg. github, linkedin are not working. Clicking on the icons does not go to the respective sites. 
### Possible issue:
I found out that the `pointer-events: none` is applied to the icon's \<a\>, making them no-op. Removing the said property from the links makes them work again.

**Comment by OfficialFindCoder** [comment]
@tusharsnn its fixed.

Thanks for the feedback
