### ISSUE TITLE
Unable to Update About Yourself in My Profile

### ISSUE THREAD

**Issue by sub1120** [OfficialFindCoder/FindCoder-Reporting-Bugs#111]
![image](https://user-images.githubusercontent.com/43786036/182386833-fdd9bb6a-8875-4d9e-a731-c93fd0260018.png)

When I clicked on save button in profile section, it showed me above error. As per error, **Username** is not allowed to be changed, but I had not changed username, I was updating **About Yourself** section. Please check this and advise.

**Comment by OfficialFindCoder** [comment]
Resolved. @sub1120 
Feel free to reopen it if you face it again or any other issue.
Thanks
