### ISSUE TITLE
Unable to edit field "expertise title" in profile, gives error message : "not possible to change username".

### ISSUE THREAD

**Issue by tayabajmal** [OfficialFindCoder/FindCoder-Reporting-Bugs#116]
Hello there !

Yesterday I was working on editing my profile at FindCoder.io and I wanted to change "expertise title" from "Web Developer" to "UI/UX Developer". Once I had made this change in the relevant field and pressed "save"-button it gives me the error "not possible to change username", but I am not changing the username. I am trying to change/edit "expertise title". 

Please see attachment for screenshot.

Kind regards

![issue_findCoder](https://user-images.githubusercontent.com/59777849/182826475-c3cb5778-5656-4629-887a-2ad2f9dfb4ec.PNG)

**Comment by OfficialFindCoder** [comment]
Resolved
