### ISSUE TITLE
When updating "About Myself" section in edit my profile - it gives error on save.

### ISSUE THREAD

**Issue by kalpeshdhotre** [OfficialFindCoder/FindCoder-Reporting-Bugs#118]
When updating **"About Myself"** section in edit my profile - it gives error **"NOT ALLOW TO CHANGE USER NAME"** on save.

<img width="1109" alt="Capture" src="https://user-images.githubusercontent.com/49611334/183076447-83a50845-187f-49aa-a539-f97e798d666d.PNG">

**Comment by OfficialFindCoder** [comment]
Resolved
