### ISSUE TITLE
Clearing search keyword after adding tag

### ISSUE THREAD

**Issue by piyushsinghania** [OfficialFindCoder/FindCoder-Reporting-Bugs#12]
@OfficialFindCoder The search keyword should be cleared after adding a tag found in search result.
This will increase the speed of adding tags and make it more user friendly.

![image](https://user-images.githubusercontent.com/69912046/147963588-bf16615b-f8e8-403b-bdc5-15fcf025049e.png)

**Comment by OfficialFindCoder** [comment]
Done
