### ISSUE TITLE
Not able to update profile details

### ISSUE THREAD

**Issue by mohdziaulhaq** [OfficialFindCoder/FindCoder-Reporting-Bugs#122]
I was trying to update my skillset and few other stuff in the Personal Details section. when I try to save my details its showing a popup saying "Not allowed to change the username" even though I did not try to change the username, I was just trying to update my skills and Bio

![errorjpg](https://user-images.githubusercontent.com/36735870/183244409-61535804-7b31-4fd3-b3e1-b99a25ced348.jpg)

**Comment by OfficialFindCoder** [comment]
@mohdziaulhaq Thanks for sharing, We have resolved the issue. 
Closing the ticket.

Happy Coding...
