### ISSUE TITLE
Projects are not visible in the profile

### ISSUE THREAD

**Issue by Shivanand0297** [OfficialFindCoder/FindCoder-Reporting-Bugs#149]
## Projects are not visible in my profile when I'm opening my profile in incognito mode.

![Screenshot 2022-08-28 085433](https://user-images.githubusercontent.com/51487163/187056046-a934ef87-81b2-42df-a47b-45f82975d526.png)

**Comment by OfficialFindCoder** [comment]
@Shivanand0297 We have fixed it.
