### ISSUE TITLE
Enhancement :   No of Comments in the Card of the Project List

### ISSUE THREAD

**Issue by ghost** [OfficialFindCoder/FindCoder-Reporting-Bugs#152]
Hi Team,

This is a small suggesstion on enhancement of the card which displays project details in project tab.  in project card we are displaying the no of users who loved this project using heart icon and no of views using eye icon.  like the above mentioned if you would shown the no of comments for the project using comment icon it would be great UX for the user.

**Comment by OfficialFindCoder** [comment]
@PonmuraliGIT please check we already have number of comment on the project cards.

**Comment by ghost** [comment]
Hi All,

Yes i saw it is there but previously it is not there.

Regards
Murali.

**Comment by OfficialFindCoder** [comment]
@PonmuraliGIT No problem, but thanks for the feedback.
Closing this issue.
