### ISSUE TITLE
Profile saving feature not working

### ISSUE THREAD

**Issue by shouvikbj** [OfficialFindCoder/FindCoder-Reporting-Bugs#153]
### Please can you look into it?

**Comment by OfficialFindCoder** [comment]
@shouvikbj are you still facing this issue?

**Comment by shouvikbj** [comment]
Yes, I am still facing the same issue.
I have tried today again and it didn't work. Status code 500 came back as
response.

Screenshot is attached below.

Please help me to complete the registration.
[image: image.png]

**Comment by shouvikbj** [comment]
The error which is showing is shown in the attached image.

**Comment by OfficialFindCoder** [comment]
@shouvikbj The picture you have uploaded is not being attached via email reply to this thread. Please open the issue thread and upload the screenshot. 
Surely will help you complete the registration.

**Comment by shouvikbj** [comment]
![Screenshot from 2022-09-06 21-12-55](https://user-images.githubusercontent.com/30182097/188689749-0db1e9d9-0fc7-44cf-8587-67f2f9ca36dd.png)

This is the screenshot of the issue.

**Comment by OfficialFindCoder** [comment]
@shouvikbj Please check if its working for you now.

**Comment by shouvikbj** [comment]
Yes. It's working fine now.
Thank you.

**Comment by OfficialFindCoder** [comment]
@shouvikbj Your welcome.
Closing this issue. Thanks
