### ISSUE TITLE
Voting system could be improved

### ISSUE THREAD

**Issue by codersgyan** [OfficialFindCoder/FindCoder-Reporting-Bugs#155]
Recently, I took participation in one of the challenges of the find coder challenges. Everything was awesome. One thing was noticed is system shows current vote count before voting by a person.
There were 10 shortlisted projects. What I noticed is, students are voting on high voted candidate base. I saw views of the remaining shortlisted candidates. Few people are not even bothering to check their projects, which is not fair comparision according to me 😊

What can be done according to me:
- Don't show the vote count before giving the vote. People should genuinely should check every project and then decide whom to vote. 

Except this, I loved this product so much ❤️

**Comment by OfficialFindCoder** [comment]
@codersgyan We will surely consider it.

Thanks for your feedback and love for [Findcoder.io](https://www.findcoder.io)

**Comment by sampatsharma143** [comment]
In my personal opinion this voting system is not right. as Tier-3 developer i was the only one from my whole class to persue computer science , software development and it is hard to find people who can vote for you.  a decent project maker can be the winner just because he/she have too many  friends, followers.

**Comment by OfficialFindCoder** [comment]
@sampatsharma143 we are working on improving it and all this will make sense after new feature roll out.
also we are monitoring for faking account votings, whoever is doing so will be disqualified and will not be allowed to participate again in upcoming challenges.
