### ISSUE TITLE
Unable to submit Projects

### ISSUE THREAD

**Issue by Chaitanya-Kaushal** [OfficialFindCoder/FindCoder-Reporting-Bugs#158]
Can you please suggest me regarding submitting projects, from last two days I am trying. 
Is it happening to me or everyone.

**Comment by OfficialFindCoder** [comment]
@Chaitanya-Kaushal Mind recording your screen while uploading the project and share?
coz no one has mentioned such an issue so far.

**Comment by Chaitanya-Kaushal** [comment]
### **I am not able to submit my projects on findcoder.** 
As you asked for recording.. Kindly check it..

https://user-images.githubusercontent.com/98635267/189258940-149e2948-e25a-45b0-b446-4ae06c70797b.mp4

**Comment by Chaitanya-Kaushal** [comment]
Still i am facing the same problem.....

video link:-
https://github.com/OfficialFindCoder/FindCoder-Reporting-Bugs/issues/158

**Comment by sudsek6060** [comment]
I am also facing the same issue.

**Comment by Chaitanya-Kaushal** [comment]
I have fixed the issue.

solution:- try not to use any special characters in projects name except
(-).  if you are using ( : ) colon remove it.  it should work..

**Comment by sudsek6060** [comment]
Okay Thank You So much..

**Comment by OfficialFindCoder** [comment]
@Chaitanya-Kaushal Its fixed. You can use : and other special chars as well.

**Comment by Chaitanya-Kaushal** [comment]
My pleasure!
