### ISSUE TITLE
Page freezes after adding thumbnail of projects 

### ISSUE THREAD

**Issue by AmanAshutosh** [OfficialFindCoder/FindCoder-Reporting-Bugs#16]
Every time I try to put a thumbnail to my project after uploading as soon try to submit the page freezes and I have to reload the complete page again in the **safari browser**, but this section is working well in **chrome**.

**Comment by masfikalam** [comment]
I'm facing the same issue in Firefox :(
Freezes both for projects and certifications

**Comment by OfficialFindCoder** [comment]
Fixed.
