### ISSUE TITLE
Years of experience calculated range (in large decimal range) 

### ISSUE THREAD

**Issue by anirudhuuu** [OfficialFindCoder/FindCoder-Reporting-Bugs#160]
Please check the following image, YOE in the given range is calculated but not rounded off

![image](https://user-images.githubusercontent.com/25549847/189466007-e3b99e94-0c6e-4e86-b376-7a71207fd4fa.png)

**Comment by OfficialFindCoder** [comment]
@anirudh-jwala Its fixed, we will roll out updates soon.
