### ISSUE TITLE
Croping part while uploading pic of project

### ISSUE THREAD

**Issue by aivy45** [OfficialFindCoder/FindCoder-Reporting-Bugs#165]
When we upload a pic and start to do croping then it will start crop vertically and horizontally both side simultaneously . So please add crop feature where we can also crop from either in vertical manner or in horizontal manner. 
![Screenshot (380)](https://user-images.githubusercontent.com/86349218/190666972-a394dda4-e596-4f0f-bf13-8f8ceb730a2a.png)

As of now we are not able to crop the pic . Even if we upload a cropped pic then that pic is not  accepted.

**Comment by OfficialFindCoder** [comment]
@aivy45 Sorry but we have strict 16:9 ratio thumbNail sizes.
