### ISSUE TITLE
Text field for Instagram username restricts speial characters

### ISSUE THREAD

**Issue by vaibhavraj-exe** [OfficialFindCoder/FindCoder-Reporting-Bugs#17]
To be specific my instagram username is vraj.py but in am not able to type in the dot ( . ) in the instagram username text field.

**Comment by sajithlaldev** [comment]
I have same issue. My instagram id is 'sajithlal.dev'. I cant type it the instagram username text field

**Comment by nitishpoonia** [comment]
I am also facing the same issue

**Comment by vaibhavraj-exe** [comment]
I can see this bug is fixed so I am closing this issue.
