### ISSUE TITLE
result of " Build A Bill Splitter" hackathon

### ISSUE THREAD

**Issue by sampatsharma143** [OfficialFindCoder/FindCoder-Reporting-Bugs#170]
When will you guys declare the result of  " Build A Bill Splitter" hackathon. it is been more thn a month.
please reply

**Comment by OfficialFindCoder** [comment]
@sampatsharma143 Sorry for the delay as the team is busy with some important features due to that result is not yet announced and it's delayed. It will be out in a day or two.
