### ISSUE TITLE
Entire code base can be viewed on the devtools

### ISSUE THREAD

**Issue by nithil** [OfficialFindCoder/FindCoder-Reporting-Bugs#18]
I can view the entire codebase on the browser devtools sources section.

Maybe move the webpack source maps to a different folder after uploading them to the error monitoring application.

<img width="590" alt="Screenshot 2022-01-04 at 18 37 50" src="https://user-images.githubusercontent.com/31035540/148063758-ab0d687c-74e0-4c59-bd7a-aff5f1871a56.png">

labels: security

**Comment by OfficialFindCoder** [comment]
Resolved 👍
