### ISSUE TITLE
Not able to edit the Email from profile

### ISSUE THREAD

**Issue by Collabalist** [OfficialFindCoder/FindCoder-Reporting-Bugs#26]
at least allow user to Edit Email and later add the verification, if Email is the primary field of social login, then please change it with the type based on user key generated, but make sure that the same email can be used in both Linkedin and Github,

**Comment by OfficialFindCoder** [comment]
As of now, we are authenticating users based on Google, Github, and Linkedin and are not validating users via email. If your email is same on any of these services, the system will check and will not create a new account for you.
As of now, there is no plan to allow users to signup or change via their custom emails.

Thanks
