### ISSUE TITLE
[BUG] Error uploading certificate images using Firefox browser

### ISSUE THREAD

**Issue by vikasganiga05** [OfficialFindCoder/FindCoder-Reporting-Bugs#36]
I can't upload my certificates images in the Certification and Awards section. The browser threw 3 client-side errors (see below screenshot). 

I am using **Firefox (v95.0.2)** browser.

### Screenshot
![Error Screenshot](https://user-images.githubusercontent.com/74750414/148081857-822f984e-935d-4e23-81a6-6b353844e94a.png)

**Comment by sebabratakundu** [comment]
I got the same issue. I can't even upload a project. 
find out firefox not support `userAgentData`. 
This is a big problem . please look into it

![image](https://user-images.githubusercontent.com/44576979/148643764-53276e9b-7412-4334-900e-ab3548068f30.png)
