### ISSUE TITLE
Experience section should be date sorted

### ISSUE THREAD

**Issue by piyushsinghania** [OfficialFindCoder/FindCoder-Reporting-Bugs#5]
@OfficialFindCoder The Experience section shows experiences as you have added them, but I believe it should be date sorted. Something like linkedIn does.

![image](https://user-images.githubusercontent.com/69912046/147945367-ed902751-b5dd-49da-a1bf-a9f50d5a18d3.png)

**Comment by OfficialFindCoder** [comment]
Thanks for your feedback. 

Sorted :)
