### ISSUE TITLE
After clicking on add project it goes to blank page.

### ISSUE THREAD

**Issue by thecoderishi** [OfficialFindCoder/FindCoder-Reporting-Bugs#51]
I signed up with google and initially, i skipped the project section, and later when i tried to add the project it goes to a blank page.
the same thing also happened with the certificate.

![add project](https://user-images.githubusercontent.com/36291789/148215215-c1d8d8cd-0962-4c1a-87ff-2b4de2c76fa7.png)

**Comment by GanapathyPT** [comment]
Yep, it also happens to me
Also It doesn't add the project or certificate to my profile anyway

**Comment by thecoderishi** [comment]
Since this issue is fixed now so I'm closing this issue.

Thanks to the team...
