### ISSUE TITLE
[security] Set a hard limit for return records in api

### ISSUE THREAD

**Issue by NithinIBhandari1999** [OfficialFindCoder/FindCoder-Reporting-Bugs#52]
Anybody can scrap easily your database:
https://www.findcoder.io/search/project/?page=1&limit=1200

For security point of view please add hard limit of 50.

**Comment by OfficialFindCoder** [comment]
> Anybody can scrap easily your database: https://www.findcoder.io/search/project/?page=1&limit=1200
> 
> For security point of view please add hard limit of 50.

@NithinIBhandari1999 Thanks for your feedback.
