### ISSUE TITLE
Add Experience Modal pop up 

### ISSUE THREAD

**Issue by lekhrajpanjwani** [OfficialFindCoder/FindCoder-Reporting-Bugs#53]
![image](https://user-images.githubusercontent.com/67046356/148375207-b42b2c99-ab33-499a-8525-0c0fa12a9654.png)

In placeholder we can see example like "Sr. Developer" but unable to enter text such as "Sr. Developer",
getting error "Special characters are not allowed". please check out above image

**Comment by OfficialFindCoder** [comment]
@lekhrajpanjwani Thanks for your feedback.

Fixed
