### ISSUE TITLE
special character issue in project description

### ISSUE THREAD

**Issue by ganeshbirajdar09** [OfficialFindCoder/FindCoder-Reporting-Bugs#55]
Cannot add special characters in the description. description is not accepting any text

**Comment by kartikkasat** [comment]
Special chars issue almost for every field...cannot enter hyperlinks of social profiles also

**Comment by thisisnitish** [comment]
Same for me as well. Special Chars are in experience fields as well. Please fix this. Allow only at necessary fields.
