### ISSUE TITLE
Free size for crop feature, while uploading images

### ISSUE THREAD

**Issue by piyushsinghania** [OfficialFindCoder/FindCoder-Reporting-Bugs#6]
@OfficialFindCoder The crop feature I guess works on 1:1, but this makes it difficult and slow to upload images. And sometimes people might not be able to upload images correctly

![image](https://user-images.githubusercontent.com/69912046/147945821-1edbf565-72f8-4c34-9fa2-4289612e3849.png)

**Comment by OfficialFindCoder** [comment]
Fixed.
