### ISSUE TITLE
Shopify tag and shopify technology is missing

### ISSUE THREAD

**Issue by vivekmp7** [OfficialFindCoder/FindCoder-Reporting-Bugs#67]
In the findcoder.io ,Under the Technology ,Shopify is missing and when create a portfolio so Shopify tag is missing 
 (https://prnt.sc/26b01s4).(https://prnt.sc/26b02cb).Please check these attachment and add these 
Thank you

**Comment by OfficialFindCoder** [comment]
Thanks for your feedback.
Added - Shopify tag :)
