### ISSUE TITLE
Old projects are gone after add new one

### ISSUE THREAD

**Issue by work4m** [OfficialFindCoder/FindCoder-Reporting-Bugs#72]
I had add 6-7 projects but after every refresh sometimes its showing 2 projects sometimes it showing 4 projects or only once I can see "more" button

**Comment by piyushsinghania** [comment]
@OfficialFindCoder same goes with me now. I am not able to see my rest porjects in my profile and everything appears to be gone. Yet when I search them in Explore Work section I can find them.

Do I need to add the projects again from scratch 😿?
Please confirm.
