### ISSUE TITLE
Can't able to upload projects from FireFox

### ISSUE THREAD

**Issue by sebabratakundu** [OfficialFindCoder/FindCoder-Reporting-Bugs#73]
**Issue Summary**

- can't able to upload a project. got an error `userAgentData`  is `undefined`

![image](https://user-images.githubusercontent.com/44576979/148643865-60173b32-55ed-40c0-8991-f1686cdf27d9.png)

![image](https://user-images.githubusercontent.com/44576979/148643857-5f9599c4-8a8c-4e36-a3b2-8f1857387ffb.png)

**Comment by OfficialFindCoder** [comment]
Fixed.
