### ISSUE TITLE
Not able to see new projects in profile!

### ISSUE THREAD

**Issue by siemen-subbaiah** [OfficialFindCoder/FindCoder-Reporting-Bugs#81]
When I add a new project from my profile, it doesn't get shown in my profile! but it does get showed to other's when viewing

EX :  (Added Images too)

My profile Project showcase has only one project, but in actual it should be two!

![image](https://user-images.githubusercontent.com/62604902/148719037-9be2ce27-0c73-4208-8f6e-b2eecce5ead2.png)

But I can see my added project when I search for it 

![image](https://user-images.githubusercontent.com/62604902/148719085-c2d819b0-2773-4278-af11-c35986f6f481.png)

**Comment by piyushsinghania** [comment]
@OfficialFindCoder Same goes with me, when I deleted one project my rest projects also vanished from my profile. Yet when I search them on the Explore Work section I can see them.

Do I will need to add up my projects again from scratch 😢
